### ISSUE TITLE
Release of v0.4.0

### ISSUE THREAD

**Issue by wildsm** [parmoo/parmoo#101]
Working through a check list as currently described at https://github.com/parmoo/parmoo/blob/release/v0.4.0/docs/dev-guide/release-proc.rst

Before release
--------------

- [x] A release branch should be taken off ``develop`` (or ``develop`` pulls  controlled).

  -  See [release/v0.4.0](https://github.com/parmoo/parmoo/tree/release/v0.4.0)
 
- [x] Release notes for this version are added to the ``CHANGELOG.rst`` file.

  -  See [CHANGELOG.rst](https://github.com/parmoo/parmoo/blob/release/v0.4.0/CHANGELOG.rst)

- [x] Version number is updated wherever it appears and ``+dev`` suffix is removed
  (in ``parmoo/version.py``, ``README.rst``, and ``docs/refs.rst``).

- [x] Check ``README.rst``: 
  - [x] *Citing ParMOO* correct?
  - [x] `docs/refs.rst`` correct?
  - [x] Coverage badge branch set to ``main`` (for badge and link)?

- [x] Check for spelling mistakes and typos in the docs and Python docstrings:
 
  - ``pyspelling -c .github/config/.spellcheck.yml``
  - Now done through CI

- [x] ``setup.py`` and ``parmoo/__init__.py`` are checked to ensure all
  information is up to date.

- [x] ``MANIFEST.in`` is checked. Locally, try out ``python setup.py sdist`` and
  check created tarball contains correct files and directories for PyPI
  package.

- [x] Check that ``parmoo`` requirements (in ``REQUIREMENTS.txt``)
  are compatible with ``readthedocs.io`` (in ``.readthedocs.yml``)

- [x] Tests are run with source to be released (this may iterate):

  - [x] On-line CI (GitHub Actions) tests must pass.

  - [x] Documentation must build and display correctly wherever hosted (currently
    readthedocs.org).

- [x] Pull request from either the develop or release branch to main requesting
  one or more reviewers (including at least one other administrator).

  - See #98 

- [x] Reviewer will check that all tests have passed and will then approve merge.

During release
--------------

An administrator will take the following steps.

- [x] Merge the pull request into main.

  - **Check that the coveralls badge is correctly updated based on main!**

- [x] Once CI tests have passed on main:

  - [x] A GitHub release will be taken from the main

  - [x] A tarball (source distribution) will be uploaded to PyPI (should be done
    via ``twine`` by an admin using PyPI-API-token authentication)

- [x] If the merge was made from a release branch (instead of develop), merge this
  branch into develop.

- [x] Create a new commit on develop that:
  - [x] Appends ``+dev`` to the version number (wherever it appears)
  - [x] Changes the coverage badge branch to ``develop`` (for badge and link).

- [x] Update the version number cited in the parMOO solver farm at
  https://github.com/parmoo/parmoo-solver-farm 
  and check that the citation, contact, etc. information there is up to date.

After release
-------------

- [x] Ensure all relevant GitHub issues are closed.

- [x] Check that the conda-forge package has tracked latest release
  and update dependency list if needed -- an admin will need to approve the
  automatically generated PR on https://github.com/conda-forge/parmoo-feedstock

**Comment by thchang** [comment]
@wildsm I checked off all the items and merged your PR on the solver farm; it looks like we just have to wait for conda forge to pick up the latest release then we can check off the last boxes and close this.  Thanks for setting this up, I've been thinking about whether we want to keep a copy of this checklist somewhere for making releases easier.
