### ISSUE TITLE
MOOP.solve() should support additional stopping criteria

### ISSUE THREAD

**Issue by thchang** [parmoo/parmoo#18]
Currently, the ``MOOP.solve()`` method can only be terminated based on number of iterations.

Additional optional arguments should be added, supporting stopping due to:
 - total simulation budget reached (perhaps even separate budgets for each simulation when dealing with multiple simulations)
 - total walltime exceeded
 - convergence criteria triggered

**Comment by brunolnetto** [comment]
@thchang the medium-level description suceeds on providing motivation for collaboration. Please, provide suggestive implementations and definitions for provided concepts for each bullet point to help guiding the developer.
