### ISSUE TITLE
README.rst needs a code coverage badge

### ISSUE THREAD

**Issue by thchang** [parmoo/parmoo#21]
It would be nice to track code coverage in ``README.rst``.

The project:  
https://github.com/dbrgn/coverage-badge

Seems promising, but we will need a place to host the badge after it has been generated.

Hosting in a gist seems like a possibility.

**Comment by wildsm** [comment]
working on coveralls solution

**Comment by wildsm** [comment]
Addressed by #92 and #94?

**Comment by thchang** [comment]
I think the right thing to do is to close this when we merge those into main
