### ISSUE TITLE
Toggle named variables

### ISSUE THREAD

**Issue by thchang** [parmoo/parmoo#23]
We should allow users to toggle whether they will use named variables, instead of choosing for them based on whether they name all design variables.

ParMOO is already set-up to do this, we just need to add a ``MOOP.use_names()`` method, or similar.

**Comment by brunolnetto** [comment]
@thchang my interpretation is: user may NOT offer an objective function name, making it optional. It does not seem recommended to expose this function for user because the library must be as lean as possible. The caveat is: user CANNOT use the same name as automatic, otherwise overwrite may occur.

**Comment by thchang** [comment]
@brunolnetto ParMOO assigns variable names automatically -- typically we recommend that users set all "name" fields, otherwise we automatically toggle off the naming.

The name fields exist though, and it would be OK for an advanced user to toggle them back on and use our default names, if they know what they are doing.

Of course, as you mentioned, users must beware of duplicate name fields if they purposefully name one of their variables to a default value, then don't use names afterward.

This would be a useful tool for developers though, since it prevents us from needing to maintain support for multiple interfaces (we can just toggle on naming before calling each new feature) -- A possible issue here is if the user created a double-naming by partially naming fields, as described above.

**Comment by brunolnetto** [comment]
These edge/corner cases suggests security flaws of low level. Setup a variable's name with previous duplicate may evoke a warning or even an error depending of designer decision. Synchronous error handling is, however, troublesome on IoT i.e. web-related usage.

**Comment by thchang** [comment]
Named variable support was dropped in v0.4.0 for other reasons, making this issue obsolete.
