### ISSUE TITLE
convert unnamed outputs to named outputs

### ISSUE THREAD

**Issue by HyrumDickinson** [parmoo/parmoo#31]
it would make things easier for the devs if there was a unified output type; perhaps a function converting unnamed outputs to named outputs would solve this

**Comment by brunolnetto** [comment]
@HyrumDickinson this issue seems somewhat old. I will add some refreshing contribution: add standard input and output schematic variables.

An alternative may be documentation refactor (README and readthedocs) to reduce verbosity and explicitate current features, if they are already available.
