### ISSUE TITLE
Similarities on direct optimization

### ISSUE THREAD

**Issue by brunolnetto** [parmoo/parmoo#51]
Hi fellows,

During my masters, I was able to develop with [my supervisor](https://scholar.google.com.br/citations?user=1pPQM4oAAAAJ&hl=pt-BR&oi=ao) a library in python language called [pybary](https://github.com/asmove/pybary). It is similar to parmoo in the sense it is a data-driven optimization method, we call it "[Barycenter Method](https://arxiv.org/abs/1801.10533)": given "unknown" oracle map $f: \mathbb{R}^n \to \mathbb{R}$ and design variables $x \in \mathbb{R}^n$, the method applies a arithmetic weighted average on these coordinates respective to weights $w_i \coloneqq e^{-\nu f(x_i)}$: it results on a coordinate close to the smallest evaluation $f(x)$ (the smaller value $f_i \coloneqq f(x_i)$, the greater weight $w_i$) for hyperparameter $\nu > 0$, or to the greatest evaluation for hyperparameter $\nu < 0$. 

It is a great opportunity to apply this method in a multi-objective scope, since it allows also a parallel procedure. Are there PhD opportunities on your laboratory?

**Comment by thchang** [comment]
Hi Bruno,

The answer depends on your situation, although it's too late for this year.  For this type of inquiry, please reach out to me directly.  You can find my email by visiting my personal webpage.  This page is for issues or suggestions related to the parmoo source code.
