### ISSUE TITLE
Gaussian_Proc - index out of bounds 

### ISSUE THREAD

**Issue by WoodKieran** [parmoo/parmoo#56]
![image](https://user-images.githubusercontent.com/106153447/233021336-6cd7d914-f91b-4b07-b9e7-664a0b93d908.png)

Forgive me if this is obvious, but this error can randomly occur and seems to have no dependence upon ParMoo input parameter choices. 

Has anyone else encountered & resolved such issue? 

Thank you in advance!

**Comment by wildsm** [comment]
@WoodKieran Thanks for flagging this, do you have some sort of minimum working example that reproduces this issue?
