### ISSUE TITLE
How many iterations?

### ISSUE THREAD

**Issue by GrandadsJumper** [parmoo/parmoo#61]
Do we have an answer to this/ a built in automatic stop point or is it a case of try 100, then try 1000 and see if theres any better solutions found on the pareto front? 

Thanks!

**Comment by thchang** [comment]
No there is no such feature at the moment.  We do need to work on adding additional stopping conditions, but there are reasons why it is not easy --

For multiobjective optimization, your solution set is typically infinite; you can always continue finding more points or improving certain points in your solution set.  It is unlikely that you will be able to achieve an epsilon tolerance for *every* possible solution point, unless you have some kind of discrete or degenerate problem.

I think that if you keep running with larger budgets as you described above, you will always continue to see some improvement in certain points or addition of new points.  If you fix one or more scalarizations (using the ``FixedWeights`` acquisition function) then you could look at improvement on those particular weightings of the objectives to see when they have stopped improving, as you said above.  However, I would strongly recommend that you still include some acquisition functions that are **not** fixed, such as the ``RandomConstraint`` method.  And if you continued optimizing, these non-fixed scalarizations, you should be able to continue identifying better points indefinitely, again, unless you happen to have an unusual problem with only a finite number of solution points.

Sorry there is not an easy answer here.

**Comment by thchang** [comment]
Typically for a *simulation* optimization problem, we assume that one has a budget of how many simulations that they can afford to run in mind, and you run until the budget is exhausted.  Also note that depending on your choice of ``SurrogateFunction`` techniques, the ``GaussRBF`` technique does not scale well if you are planning on taking over ~3k simulation evaluations.  In the current library, ``LocalGaussRBF`` (should be paired with ``TR_LBFGSB`` optimizer) is the most scalable option if you plan to take a very large budget (e.g., approaching 10k sim evals)
